### ISSUE TITLE
How to run your system?

### ISSUE THREAD

**Issue by mlotysz** [ArekArek/Pat2016_Arkadiusz_Kamasa#5]
Minimal documentation is needed. I cloned your repo and... Use README.md for that.

**Comment by mlotysz** [comment]
Cool.
One thing: readme.md it's not an markdown format. Fix that. You can use https://raw.githubusercontent.com/blstream/AugumentedSzczecin_java/master/README.md as an example.

**Comment by ArekArek** [comment]
I added a few tabulators before commands and I think it works. Commit 6 - 05.01.2016 22:47
