### ISSUE TITLE
Invalid package name for classes

### ISSUE THREAD

**Issue by mlotysz** [ArekArek/Pat2016_Arkadiusz_Kamasa#6]
Change `Baza.Baza1` to something meaningful. Use: http://www.dropwizard.io/0.9.1/docs/manual/core.html#organizing-your-project as an example.

**Comment by ArekArek** [comment]
I have updated it in  Commit 6 - 05.01.2016 22:47

**Comment by mlotysz** [comment]
You used `com` as package name. Is invalid.
1. Check: https://maven.apache.org/guides/mini/guide-naming-conventions.html for maven side. Update in pom.xml and then
2.  use groupId.artifactId as main java package name.

**Comment by ArekArek** [comment]
Renamed according to Maven site advice. Commit 7 07.01.2016 18:50

**Comment by mlotysz** [comment]
It's better but take into account: http://stackoverflow.com/a/8243348: TL;DR Package names should be all lowercase characters whenever possible. (This is last issue to resolve first task: good job!)

**Comment by ArekArek** [comment]
Ok, i changed that. Commit 8 07.01.2016 21:13
