### ISSUE TITLE
Missing request validation

### ISSUE THREAD

**Issue by mlotysz** [ArekArek/Pat2016_Arkadiusz_Kamasa#8]
For e.g. this invalid request is not handled well:
```
curl -H "Content-Type: application/json" \
-X POST \
-d '{"name":"AAA","yearOfProduction":"BBB"}' \
http://localhost:8080/movies
```
Server returns HTTP 500. It should return HTTP 4xx code with some minimal error message. Fix all your representations. You can check http://www.dropwizard.io/0.9.1/docs/manual/validation.html#man-validation first.

**Comment by ArekArek** [comment]
I added @NotEmpty annotations at initializing fields like "name" in Actor and Movie. Commit 05.01.2016 19:26
